logo_link_target:
  default: ""
  type: string
  description: "Link target for logo in the header"
logo_alt:
  default: "siio.de"
  type: string
  description: "Alternative text to display for the top left image"
ad_banner_img:
  default: ""
  type: string
  description: "URL to the ad banner picture in the header"
ad_banner_link:
  default: ""
  type: string
  description: "Link target of the ad banner in the header"
footer_imprint_link:
  default: ""
  type: string
  description: "Link target for imprint link in the footer"
footer_privacy_link:
  default: ""
  type: string
  description: "Link target for privacy link in the footer"
footer_coop_link:
  default: ""
  type: string
  description: "Link target for cooperations link in the footer"
