logo_url:
  default: ""
  type: string
  description: "This is the source link to the top left logo"
logo_alt:
  default: "siio.de"
  type: string
  description: "Alternative text to display for the top left image"
ad_banner_img:
  default: ""
  type: string
  description: "URL to the ad banner picture in the header"
ad_banner_link:
  default: ""
  type: string
  description: "Link target of the add banner in the header"
