show_top_banner_bar:
  type: bool
  default: true
  description: "Enable or disable the banner bar at the top of the page"
top_banner_bar_image:
  default: "https://b9esmv0.myraidbox.de/wp-content/uploads/2019/09/2power-by-Aeotec.png"
  type: string
  description: "URL to the ad picture in the banner bar"
top_banner_color:
  default: "#9B9B9B"
  type: string
  description: "Background color of the top banner bar (hex)"
show_header_banner:
  type: bool
  default: true
  description: "Enable or disable the header banner"
logo_link_target:
  default: ""
  type: string
  description: "Link target for logo in the header"
logo_alt:
  default: "siio.de"
  type: string
  description: "Alternative text to display for the top left image"
ad_banner_img:
  default: "https://dummyimage.com/600x100/CCC/ffffff.png&text=ad+banner+(600x100)"
  type: string
  description: "URL to the ad banner picture in the header"
ad_banner_link:
  default: ""
  type: string
  description: "Link target of the ad banner in the header"
footer_imprint_link:
  default: ""
  type: string
  description: "Link target for imprint link in the footer"
footer_privacy_link:
  default: ""
  type: string
  description: "Link target for privacy link in the footer"
footer_coop_link:
  default: ""
  type: string
  description: "Link target for cooperations link in the footer"